# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [16]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [17]:
iris = datasets.load_iris()

In [18]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [19]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [5]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [6]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 4.6  3.4  1.4  0.3]
 [ 5.   2.   3.5  1. ]
 [ 6.4  3.2  5.3  2.3]
 [ 5.   3.3  1.4  0.2]
 [ 5.6  2.5  3.9  1.1]]


Тестовая выборка:
[[ 5.2  4.1  1.5  0.1]
 [ 7.1  3.   5.9  2.1]
 [ 5.1  3.5  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.1  3.7  1.5  0.4]]


In [7]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[0 1 2 0 1 1 2 1 0 1 1 1 2 0 1 0 1 1 0 0 0 1 2 2 0 0 2 1 1 1 0 2 2 1 1 0 0
 2 2 0 1 1 1 0 0 2 2 0 2 2 0 2 0 2 2 0 0 2 2 0 1 2 0 1 1 1 1 2 1 1 0 0 2 2
 0 1 2 2 1 0 1 1 0 2 0 0 1 2 0 1 0 1 2 2 2 1 2 1 2 2 1 0 2 2 1]


Метки классов на тестовой выборке:
[0 2 0 0 0 0 0 2 2 1 2 1 1 0 2 2 2 0 1 1 1 2 2 1 2 0 0 2 2 0 0 2 1 2 0 0 0
 2 1 0 1 0 1 1 1]


### Стратегии проведения кросс-валидации

#### KFold

In [23]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [22]:
#многократный запуск приводит к различным разбиениям
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

[0 2 3 7 8] [1 4 5 6 9]
[1 4 5 6 9] [0 2 3 7 8]


In [24]:
#многократный запуск приводит к одному и  тому же разбиению, результат запуска детерминированный
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [25]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [26]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[1 2 3 4] [0 5 6 7 8 9]
[0 5 6 7 8 9] [1 2 3 4]


#### ShuffleSplit

In [27]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

[4 3 0 7 8 1 5 6] [9 2]
[5 7 4 2 9 8 0 6] [1 3]
[3 2 6 8 4 9 1 7] [0 5]
[0 9 5 6 7 8 1 2] [3 4]
[4 1 7 6 9 0 5 2] [3 8]
[4 0 1 5 9 3 8 2] [6 7]
[2 7 8 9 3 0 1 5] [4 6]
[4 8 0 2 7 9 3 5] [6 1]
[1 8 0 2 4 6 3 7] [9 5]
[7 9 2 8 4 5 0 1] [6 3]


#### StratifiedShuffleSplit

In [14]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[6 8 3 1 9 7 4 0] [5 2]
[9 4 7 3 1 6 8 0] [5 2]
[5 1 2 8 0 3 6 9] [4 7]
[7 3 4 8 9 0 5 2] [1 6]


#### Leave-One-Out

In [15]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators